name: Velm-VT CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gcc, clang]
        build_type: [Debug, Release]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build lcov libglfw3-dev pkg-config libhdf5-dev libgtest-dev

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install cmake ninja pkg-config glfw hdf5 googletest

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install -y cmake ninja pkgconfiglite glfw hdf5

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake -G Ninja \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DCMAKE_C_COMPILER=${{ matrix.compiler }} \
                -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}++ \
                ..

      - name: Build
        run: cd build && ninja

      - name: Run Tests
        run: cd build && ctest --output-on-failure

      - name: Upload Coverage
        if: matrix.os == 'ubuntu-latest' && matrix.compiler == 'clang' && matrix.build_type == 'Debug'
        run: |
          cd build
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          lcov --list coverage.info
          bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov upload failed"
