name: Velm-VT CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Debug, Release]
        include:
          - os: ubuntu-latest
            compiler: gcc
          - os: ubuntu-latest
            compiler: clang
          - os: macos-latest
            compiler: clang
          - os: windows-latest
            compiler: msvc
    name: ${{ matrix.os }} | ${{ matrix.compiler }} | ${{ matrix.build_type }}
    steps:
      - uses: actions/checkout@v3

      # Install dependencies
      - name: Install Dependencies
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            if [[ "${{ matrix.compiler }}" == "gcc" ]]; then sudo apt-get install -y build-essential cmake ninja-build lcov; fi
            if [[ "${{ matrix.compiler }}" == "clang" ]]; then sudo apt-get install -y clang cmake ninja-build lcov; fi
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew install cmake ninja
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            choco install cmake ninja
          fi

      # Configure CMake
      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake -G Ninja \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DCMAKE_C_COMPILER=${{ matrix.compiler }} \
                -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}++ \
                ..

      # Build project
      - name: Build
        run: cd build && ninja

      # Run tests
      - name: Run Tests
        run: cd build && ctest --output-on-failure

      # Coverage reporting (Linux/Clang only)
      - name: Upload Coverage
        if: matrix.os == 'ubuntu-latest' && matrix.compiler == 'clang' && matrix.build_type == 'Debug'
        run: |
          cd build
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          lcov --list coverage.info
          bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov upload failed"
